### ISSUE TITLE
Submission: Project Plan

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#1]
Each Team is required to submit a 1-4 page PDF into the relevant LMS Dropbox folder by 23:59 on the 21st of May 2023. This plan will be 5% of your overall grade. 

However, it will also be used as a reference for the final
submissions. Specifically, in the final report you will be required to reflect on your project’s progress in relation to this plan, noting changes to it that occurred along the way.

Overall, the plan should be as comprehensive and realistic as it can be, based on the best information that you have at the time. You cannot be penalized for the client changing requirements, which subsequently alter your plan, but you will be marked on how well you mitigate changes and reflect on them in the final report.

**Comment by danialhbma** [comment]
Project objectives completed

**Comment by danialhbma** [comment]
In progress:
- Project board
- Gantt chart
- Job distribution

**Comment by yucan-yu** [comment]
Gantt chart 1st complete draft complete, to be reviewed by team.
