### ISSUE TITLE
Implementation: Docker Containers

### ISSUE THREAD

**Issue by ong-yi-xuan** [danialhbma/ITP-SE12-Power-Monitoring#10]
Figure out how to use Dockers for:  
•  InfluxDB @Yapping72 
•  Grafana @danialhbma @yucan-yu 
•  MQTT Broker @ong-yi-xuan 
•  Tuya Cloud @chococtea @yucan-yu 
•  Node-RED @ong-yi-xuan

**Comment by ong-yi-xuan** [comment]
Using cloud broker (HiveMQ) for MQTT, so docker container is not needed.
To add: documentation on cloud broker and how to connect

**Comment by ong-yi-xuan** [comment]
team is currently using node-red docker from https://hub.docker.com/r/nodered/node-red

**Comment by yucan-yu** [comment]
InfluxDB container hosted on Google Cloud, completed by @Yapping72

**Comment by ong-yi-xuan** [comment]
Completed:
- MQTT broker moved off HiveMQ due to limited data traffic per month and easier management on single cloud platform
- Eclipse MQTT container and Node-RED container hosted on Google Cloud, completed by @Yapping72

In progress:
- Node-RED configuration for Tuya sockers by @chococtea and sensors by @ong-yi-xuan

**Comment by ong-yi-xuan** [comment]
Authentication for clients connecting to MQTT broker on Google Cloud configured successfully and tested ✅

**Comment by ong-yi-xuan** [comment]
Node-RED configuration for sensors completed ✅

**Comment by yucan-yu** [comment]
Expanded in issue #22.
