### ISSUE TITLE
Research: Container Farm Visits

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#13]
List of things to do on 2nd visit:

1. Take photos of the container, the racks, power sockets, plants, and various wiring connections
2. Obtain the answers to the following questions through our visit:
    - How many racks are there in one container?
    - How many power sockets are in use per rack?
    - Is there only one aircon in a container?
    - How many rows are there in one rack?
    - How many light strips per row on a rack?
    - What is the schedule of the timer on the power sockets?

**Comment by danialhbma** [comment]
Summary of 2nd visit to the farm:

Situation in the container:
Lights:
1. Each rack has 15 lights 
(1 rack = 3 rows, 1 row = 5 lights)

2. All 15 lights connected to 1 socket
(So turning off/on the socket affects all lights in the rack)

3. The socket for the light is the one with the timer on it.

4. The timer is set to turn the light on at 7am and turn off at 7pm for each rack everyday. 
(So, 7am - 7pm is the period of time that the light is on)

5. Some of the lights are in different colors (white or pruple?) depending on the plants. Need to test out if got difference in power consumption etc.

Water Pump:
1. Each rack has 1 water pump (The brown container at the bottom of the rack).

2. Each row has a green tube (where water comes in) at one end and a drainage at the other end.

3. The water pump is always turn on (if not, water overflows). Except for when they want to change the water. (They change water manually)

4. Excess water is drained back into the container. (so, from container to the row back to the container)

Aircon:
1. There is 2 aircons for each container.

2. Both aircons are always turn on at 17°C unless the staff change the temp due to special reasons.

3. The RP staff was unsure where the main socket is for the aircons. 
(so, not too sure where to put the Tuya socket or the clamp)

Plants:
1. They usually grow 4-5 types of plants in 1 container.

2. They say the plants can all grow in the same temperature. (so, 17°C)

3. They say they change the plants in the rack every 4 weeks.

Installation Notes:
1. We are only allowed to work on the front 3 racks (closest to the door) since they say not to touch the other racks.

2. We can have extension plug but it must be at the top of the rack and must be very secured. 

3. The racks and floor may get wet sometimes due to power shortage or moving etc. So, be extra careful with the placing of the hardware.

4. We have to be very quick since the water overflow quite fast when the power for water pump is off.

5. We will need zipties, longer usb cables, extension plug, maybe adapter for the flow sensor (green tube too small), usb hubs and adhesive tapes for our setup.

Power Consumption: (The Email RP Sent)
1. They are using only 1 power meter to measure all container farms + greenhouse. So, the data they give is not specific to the container farms only.

Additional Notes: (Might/Might not be useful)
1. There's a fan at one end of the container which the RP Staff used for her Strawberry plants. She turns it on sometimes for pollination. 

2. The lights on the ceiling will be turned of/on depending on the situation. 
(For example: night visits)

3. The lights for the greenhouse is set up by the RP Staff. So, no fixed schedule.

**Comment by danialhbma** [comment]
After the 2nd visit, the team has different plans for the hardware installation as the number of devices that can be measured is not what we expected. As such, the team will discuss with Prof Fauzi on how to approach the hardware installation before the 3rd visit.

**Comment by yucan-yu** [comment]
All requirements gathered, refer to #17 for 3rd visit with regards to installation.
