### ISSUE TITLE
Implementation: Configure Node-RED

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#15]
Configure Node-RED to write to database.

**Comment by ong-yi-xuan** [comment]
work in progress:
- research and test out dynamic subscription on node-red (so node-red can automatically send data from MQTT topic to influxdb, instead of manually selecting topic and influxdb location each time)
- research if node-red can allocate tags for clearer separation of data in influxdb

**Comment by ong-yi-xuan** [comment]
node-red unable to allocate tags for influxdb

**Comment by ong-yi-xuan** [comment]
research and test out dynamic subscription on node-red to be moved to sprint 2 after rapsberry pi has been set up

**Comment by yucan-yu** [comment]
^ refer to issue #16 for updates
