### ISSUE TITLE
Implementation: Configure RP4

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#16]
Configure RP4 as per architecture, running on balenaOS so other team members can monitor the pi remotely

**Comment by ong-yi-xuan** [comment]
balenaOS set up on raspberry pi ✅

**Comment by yucan-yu** [comment]
Review to be conducted on 310323, Wednesday.

**Comment by ong-yi-xuan** [comment]
after review, team has decided to move RP4 operations onto Google Cloud for ease of management

the following services will be running on Google Cloud:
- influxDB
- MQTT broker
- Node-red
