### ISSUE TITLE
Implementation: Installation of Hardware Components

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#17]
Description provided by @danialhbma in first comment below.

**Comment by danialhbma** [comment]
The team will be installation the hardware components on the farm on 19th June 2023, Monday and will begin collecting data from then onwards

**Comment by yucan-yu** [comment]
Items retrieved from Prof Fauzi:
- 3x extension cord
- 5x 2m USB-A to USB-C cables
- 3x plug head (USB-A port)
- 1x 1m USB-A to micro USB
- 1x USB hub
- 1x M5StickC with TVOC / CO2 unit
- 1x roll of cling wrap

Additionally, will require:
- 6x power banks collected by @chococtea
- Various components held by each member respectively

See everyone on Monday :)

**Comment by yucan-yu** [comment]
All current hardware components installed as of 190623, 1800 hrs.
✅ Data successfully sending as per set interval.

Members to continue monitoring database and report any sudden stoppages of transmission.
