### ISSUE TITLE
Implementation: Optimisation of Power Usage for M5Stick

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#19]
Explore ways to reduce power usage of M5Stick, so it can last longer when deployed in the container farm.

**Comment by ong-yi-xuan** [comment]
reduce power usage of M5Stick by:
- sending data once per hour
- putting device to sleep when not in use
- removing unneeded display text

code pushed to github repo
testing in progress

**Comment by ong-yi-xuan** [comment]
after testing: if router is down/unavailable, ran into issue where m5stick is stuck on reconnecting to wifi and needs user to manually press button for it to reconnect

to add:
- after m5stick comes out of sleep, make sure wifi is connected
- if wifi not connecting, attempt reconnection every minute
- ui/menu for m5stick > click click buttons to choose rack and readings instead of hardcoding it for each m5stick

**Comment by ong-yi-xuan** [comment]
added automatic connection to wifi ✅

**Comment by yucan-yu** [comment]
@ong-yi-xuan, below tested and working:
- Sending data only once per hour ✅
- Putting device to sleep when not in use ✅
- UI/menu for M5Stick - refer to issue #24 ✅
- Automatic connection to Wi-Fi ✅

TODO: turn off unnecessary components with deep_sleep(duration) function in main.py, suggest:
1. LCD / LED
2. Speaker
3. Buttons
4. Anything else deemed fit

**Comment by ong-yi-xuan** [comment]
the following unnecessary components are turned off and/or disconnected from within the deep_sleep function in main.py:
1. LCD backlight turned off ✅
2. disconnect from mqtt before sleep ✅
3. disconnect from wifi before sleep ✅

**Comment by yucan-yu** [comment]
Sorry, M5StickC doesn't have a built-in speaker. Thanks for disabling the identified components we're using during deepsleep @ong-yi-xuan.

Adding on a suggestion to shorten deepsleep duration to 30 minutes due to updated installation plan; cheers.

**Comment by ong-yi-xuan** [comment]
shortened deepsleep duration to 30 minutes ✅
pushed codes ✅

testing in progress

**Comment by yucan-yu** [comment]
Apologies for the late update:
- Code tested to be working as intended by @ong-yi-xuan and @yucan-yu.
- Power consumption monitored by @danialhbma and proven to be optimised.
