### ISSUE TITLE
Research: Literature Review

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#2]
- Current solutions to monitor power usage.
- Test out different power monitoring devices
- Research on existing solutions. How they do it, pros / cons. Why the solution is good/bad

**Comment by danialhbma** [comment]
Literature review should cover the limitations of the container (limited power consumption data) and also our workaround solutions to the variances around this.

**Comment by danialhbma** [comment]
Will also cover the different devices (power monitoring sockets) and power meter clamp as alternatives to the final devices that we are using in the containers.

**Comment by danialhbma** [comment]
Including NEA weather data as another point of research, and also why OpenWeather was chosen (see Implementation: Weather API for more information)

**Comment by danialhbma** [comment]
Each decision made needs to be explained and justified, for example:

- Why InfluxDB and not others
- Why Tuya devices and not others
- Why OpenWeather (and how accurate is it compared to NEA since it's not local)
etc.

**Comment by danialhbma** [comment]
Each member is to write the literature review on the types of technology that they used for the project (example: why @ong-yi-xuan  used m5stick c)

**Comment by danialhbma** [comment]
Literature review will cover the following choices that we made throughout the project:
Tuya	
IoT (hardware choices)	
External Temperature Reading	
Time-Series Database
Cloud vs Raspberry Pi
Balena Cloud vs Google Cloud

**Comment by danialhbma** [comment]
Literature review on External Temperature Reading completed, covers:

OpenWeather	- Free vs Historical paid version
National Environmental Agency Climate Information & Data - Realtime vs Historical	
Other methods - Hardware 
Final decision

**Comment by ong-yi-xuan** [comment]
literature review on server deployment options 90% completed, covers:
- native raspberry pi
- balena
- google cloud platform
- reliability, security and scalability of all 3 above options

wip:
- summary of options + final decision

**Comment by danialhbma** [comment]
literature review on power monitoring solutions completed, covers:
- Sonoff USB Smart Adapter 
- Broadlink SP2 e-plug 
- YHDC SCT-013-000 Current Transformer
- Review or resources

the rest of this section was completed by @chococtea

**Comment by danialhbma** [comment]
Literature review section about 90% completed.

Remaining sections:
- 2.4 Database, Review of resources
- 2.5.3 Deployment, Back-end technologies 

Incomplete/requires more elaboration:
- 2.2 Monitoring Internal Environmental Data (not sure if the content written is correct, need someone else to review)
- 2.5.2 Deployment, Front-end technologies (at least 1 more source other than Grafana)

**Comment by yucan-yu** [comment]
Section 2.2 reviewed and edited.

**Comment by danialhbma** [comment]
- Rewrote section 2.1.1.
- Wrote Section 2.3.3 on sensors (previously only covered MCUs)
- Reviewed and edited multiple sections according to Prof. Fauzi's comments, such as removing the price on some tables and adding meaningful columns.

Final subsection left to be completed:
2.4.4 Review of resources (for database)

**Comment by danialhbma** [comment]
all sections completed, will close issue when approved by Prof Fauzi.

**Comment by danialhbma** [comment]
all literature review sections reviewed and completed.
