### ISSUE TITLE
Implementation: Weather API

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#20]
To explore OpenWeather / NEA Weather API to retrieve hourly temperature around the RP greenhouse area.

**Comment by yucan-yu** [comment]
To update team and HOTO code with @ong-yi-xuan after retrieval (that is completed and tested).

**Comment by danialhbma** [comment]
Example of dataset given from the OpenWeather API:
{'coord': {'lon': 103.7823, 'lat': 1.4474}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 31.27, 'feels_like': 37.4, 'temp_min': 29.6, 'temp_max': 33.35, 'pressure': 1006, 'humidity': 67}, 'visibility': 10000, 'wind': {'speed': 3.6, 'deg': 150}, 'clouds': {'all': 75}, 'dt': 1686471348, 'sys': {'type': 1, 'id': 9479, 'country': 'SG', 'sunrise': 1686437905, 'sunset': 1686481833}, 'timezone': 28800, 'id': 1882316, 'name': 'Woodlands', 'cod': 200}

After curation, these are the required fields identified:
Weather Main - Describes weather condition
Temperature - Affects cooling/heating demands
Feels Like - Considers factors like humidity and wind, providing a more accurate measure of the weather
Pressure - Atmospheric pressure can indirectly influence energy consumption by affecting air density and thus potentially impacting heating, ventilation, and air conditioning (HVAC) systems' efficiency
Humidity - Higher humidity = more energy required to remove moisture
Cloudiness - The degree of cloudiness affects solar radiation, which is crucial for solar energy systems, as clouds can reduce the amount of sunlight available and subsequently impact energy production

Example of 1 API call:
Weather Main: Rain
Temperature: 31.65 C
Feels Like: 38.08 C
Pressure: 1006 hPa
Humidity: 66%
Cloudiness: 75%

**Comment by danialhbma** [comment]
Current issue:

**OpenWeather**
OpenWeather provides basic access to current weather data but not historical data. If we want to perform an analysis on historical data that aligns with our energy consumption data (~1 year ago) we need to pay for the subscription plan that allows access to the past ~40 years of data (120 GBP, which is ~$203 SGD per month). 

Pros - A lot of data points to draw conclusions from (see previous comment)
Cons - Data only starts from the date of collection. June - Aug will provide us with 3 months of weather statistics that occur during the summer (peak temperatures in SG) and not the cooler periods like Dec-Jan.

**NEA**
Very rough data such as mean, min, max temp, min, max wind speed, and rainfall measurements. 

Pros - Some historical data to work with, all the data in a .csv file.
Cons - Dataset covers 2011-07-10 to 2017-11-19. Cannot pinpoint a specific location (no lat, long input values)

**Current plan going forward**
Use OpenWeather to obtain hourly data and send it to InfluxDB for the next few months. Our final analysis can find some way to include NEA dataset for our pattern observation for periods that we cannot cover.

Idea: Create VM instance on Google Cloud -> python script with OpenWeather API and send output to InfluxDB (with connection details in script) -> schedule the script to run hourly using cron

**Comment by danialhbma** [comment]
Updated plan for weather data after discussion:
1. Collect hourly weather data until Aug using OpenWeather
2. If we do get energy consumption data, we will use http://www.weather.gov.sg/climate-historical-daily/ to collect data and align it with the energy consumption dates for our final analysis.

No plans on how to use the NEA dataset yet, will probably only include in the Literature Review for our final report.

**Comment by danialhbma** [comment]
Update: @Yapping72 to create cron schedule to start collecting weather data

**Comment by Yapping72** [comment]
1. Created OpenWeatherMapAPIClient and InfluxDBMeasurement classes to facilitate API calls and writing to DB respectively. 
2. Added CRON job scheduler that runsOpenWeatherMapAPIClient.py at the 10th minute of every hour i.e., 1 hourly intervals, but with 10 minute buffer to ensure OpenWeatherMapAPI has suficient time to update their readings.
3. Verified that cron job working for 1 minute intervals, have yet to verify if 1 hour intervals work, will monitor and update accordingly.

**Comment by Yapping72** [comment]
Change CRON expression to run script at start of every hour instead of 10th minute of every hour, OpenWeatherMapAPI has live weather data hence no need to add buffer time.

**Comment by Yapping72** [comment]
Changed CRON expression to run script every 30 minutes instead of once every hour.

**Comment by Yapping72** [comment]
CRON jobs to schedule OpenWeatherMap  API calls every 30 minutes works
Writing API responses to InfluxDB works
