### ISSUE TITLE
Implementation: Grafana

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#21]
Set up Grafana with InfluxDB as its data source for real-time monitoring, and explore additional capabilities that can be provided and is suitable for our use case.

Refer to #6 for research findings.

**Comment by Yapping72** [comment]
1. Hosting grafana server on port :3000. 
     - http://35.198.233.52:3000
2. Created and merged docker-compose files

WIP: Adding InfluxDB as datasource.

**Comment by yucan-yu** [comment]
Created a test dashboard and successfully retrieved data from InfluxDB via Flux query.


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91590888/cba6f574-86ba-48c7-bfb2-d87c4a29f458)

**Comment by yucan-yu** [comment]
**Sample query syntax:**
from(bucket: "Water")
  |> range(start: 2023-06-15T00:00:00Z, stop: 2023-06-17T00:00:00Z)
  |> filter(fn: (r) => r._measurement == "rack1_water")

**Comment by Yapping72** [comment]
Added 24-hr visualization for:

- Growlight power consumption and light intensity
- farm temperature and outdoor min, max, feels like and temp
- farm humidity and outdoor humidity
- water pump power consumption and water flow readings
- co2 levels, outdoor cloudiness and outdoor atm pressure. 

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/54227281/b3f79883-4e07-4105-87c9-b2004582af73)

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/54227281/25cbc65f-bde8-44f8-aca6-30088d8165cf)

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/54227281/cc27b925-f6e1-495c-907b-527356533d08)

Team to discuss on beautifying grafana and what the crop scientists actually needs.

**Comment by yucan-yu** [comment]
Closing this issue. To create separate issues for specific Grafana implementations, currently:
1. @Yapping72 to implement filters - followed up on issue #25.
2. @yucan-yu to implement monthly report - followed up on issue #26.
