### ISSUE TITLE
Implementation: Generate Monthly Report (Grafana)

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#26]
Research and enable Grafana to generate monthly reports on various data collected.

**Comment by yucan-yu** [comment]
Moved to Sprint 3 and reassigned to @danialhbma due to sudden client request and time limitations.

**Comment by danialhbma** [comment]
Issue pushed back to Sprint 4, will revisit the idea again & determine if required.

**Comment by danialhbma** [comment]
Report completed, code takes in generated images from the analysis/results folder and outputs the report to the analysis/reports folder. Files will be generated as Analysis_Month_Year.pdf. Might do some touchups with the report layout, but for now it works.

**Comment by danialhbma** [comment]
Report generation code updated & report format changed:

- Analysis_Month_Year (e.g., Analysis_July_2023) will represent the analysis based on data we collected (no prediction at all)
- Estimation_Analysis_Month_Year (e.g., Estimation_Analysis_July_2023) will represent any prediction, correlation or estimation that we did based on the data collected & other external values (e.g., estimated power consumption)

**Comment by danialhbma** [comment]
Report refined again.

- First section (Historical Analysis) will contain the analysis of data collected on the farm (variables that affect power consumption)
- It will also include the cost-efficiency analysis of the best periods to grow the plants

- Second section (Prediciton Analysis) will contain all the remaining analyses, such as the predicted power consumption and cost. These analyses are based on a mix of data sources (external temperature API, historical weather data, and also predictions based on some training models)
