### ISSUE TITLE
Research: Hardware Components

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#3]
Decide on the required MCU, sensors, actuators, etc.

For now, we have decided on:

1. **M5StickC Plus**

Used to measure  
- Carbon Dioxide 
- Measure Temperature
- Humidity
- Light

There will be multiple M5Sticks to be used.

2. **Smart Energy Meter [Model: 炬为电能宝-计控型(S1WP)]**

Used to measure  
- Energy usage
- Power Efficiency

**Comment by danialhbma** [comment]
In progress:

- Find a suitable Power Clamp Meter that can send data to the m5 stick

Power Clamp Meter that can interface with Tuya rejected. Have to find another one that can simply interface and send data to the m5stick instead of collecting the data on the Tuya cloud.

**Comment by danialhbma** [comment]
See if this product can send the same data as the original power plug:
https://www.lazada.sg//products/i1653497943-s11510309869.html?spm=a2o42.cart.0.0.4a087a93is7uVS&urlFlag=true

And get back to Prof. Fauzi if it's a working alternative that we can use.

**Comment by yucan-yu** [comment]
Looking into following ADCs (for water flow sensor) due to compatibility with M5:
1. https://shop.m5stack.com/products/adc-unit
2. https://shop.m5stack.com/products/m5stickc-adc-hat-ads1100

**Comment by yucan-yu** [comment]
Got the M5 ADC Unit and the YF-S201 water flow sensor.
