### ISSUE TITLE
Implementation: Enhance Crop Scientist Dashboard

### ISSUE THREAD

**Issue by Yapping72** [danialhbma/ITP-SE12-Power-Monitoring#31]
Create / updating existing dashboard such that it is more intuitive for Crop-scientist. Dashboard should be tailored towards the Crop scientist POV.

**Comment by Yapping72** [comment]
Updated crop scientist dashboard to show most-recent readings, show period when growlights and water pump sensors were active for. Team to explore alternatives on how dashboard can be configured and what other elements should be displayed.

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/54227281/c616b7d8-96df-4385-aca1-b65757a516df)

Removed the 24-hr naming convention for charts in dashboards since grafana allows users to custom filter through dates / period. 
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/54227281/5e4dd69c-043a-48e3-bd74-c165a5428d5f)

**Comment by danialhbma** [comment]
Add on an image that shows the floorplan of the racks and devices

**Comment by Yapping72** [comment]
Send to crop scientist for their input.

**Comment by Yapping72** [comment]
To Add image showing layout of farm and to create a new dashboard that shows all information pertaining to 1 rack. @ong-yi-xuan

**Comment by ong-yi-xuan** [comment]
created floor plan of racks and devices

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/e7b44440-de92-4cdd-8c58-b2c52bd02482)

**Comment by ong-yi-xuan** [comment]
- modified floor plan to include tuya devices that monitor power consumption ✅
- added new dashboard into grafana with: floor plan +  all information pertaining to 1 rack ✅

updated floor plan:
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/7256c604-4de6-4990-9a6b-149d2f975d4b)

**Comment by ong-yi-xuan** [comment]
updated grafana dashboard following feedback from itp supervisor:
- changed "Installation Layout" to "Deployment Layout" ✅
- modified graph labels to be clearer to users ✅
- normalized graphs ✅

**Comment by ong-yi-xuan** [comment]
update deployment layout diagram ✅


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/4377d477-8e20-4b38-b37b-34164c310614)

**Comment by danialhbma** [comment]
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/92083488/65f0db84-fbd4-4fec-9809-70ea5b6f907c)

Discovered that we got the layout of the container wrong. There are 5 racks on the top row and 4 racks below. Rack 3 should be on **the second from the left** rack in the updated layout.

**Comment by ong-yi-xuan** [comment]
updated diagram according to findings

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/ecc5cf83-ee48-45da-8acc-1e4480bfc216)

**Comment by ong-yi-xuan** [comment]
grafana dashboard updated with new diagram

**Comment by ong-yi-xuan** [comment]
diagram updated again to more accurately show position of racks relative to door. updated in grafana dashboard:


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/2ccbfff4-f107-4ae1-84c9-b06defe6efdf)
