### ISSUE TITLE
Submission: Final Report

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#32]
Each member is to write on the parts that they worked on this project for:

- Literature Review
- Systems Test
- Concepts Applied

**Comment by yucan-yu** [comment]
Completed sections on:
1. SEN0217 (under Systems Test)
2. OOP (under Concepts Applied)

Currently working on:
1. Software Architecture (under Proposed Design)
2. Software Architecture (under Concepts Applied)

**Comment by yucan-yu** [comment]
Pushed back Software Architecture (under Proposed Design) to work on Agile Methodology (under Concepts Applied) first.

Completed sections on:
1. Agile Methodology (under Concepts Applied)
2. Software Architecture (under Concepts Applied)

Currently working on:
1. Literature Review
2. Software Architecture (under Proposed Design)
3. Hardware Testing

**Comment by danialhbma** [comment]
Completed sections on:

**Under Literature Review**
1. External Environmental Data
- OpenWeather
- NEA
- Other sources 
- Review of resources 

2. Power Monitoring 
- Sonoff USB Smart Adapter 
- Broadlink SP2 e-plug
- YHDC SCT-013-000 Current Transformer

Currently working on:
1. Abstract
2. Introduction 
3. Power Monitoring (excluding Tuya devices)
4. Internal Environmental Data 
5. Systems Test - OpenWeather API, m5stick sensors

**Comment by danialhbma** [comment]
Completed sections on:

**Under Literature Review**

- Power Monitoring (excluding Tuya devices)
- Review of Power Monitoring resources 
- External environmental data - Meteorological Service Singapore: Historical Weather Data 
- Database: MongoDB

**Under Deployment**
- External Environmental Data 

Currently working on:
- Abstract
- Introduction
- Literature review - Internal Environmental Data
- Systems Test - OpenWeather API, m5stick sensors

**Comment by yucan-yu** [comment]
Will complete Software Architecture section after Literature Review is all complete.

Completed sections on:
1. SEN0217 Water Flow (under Systems Test, previously known as Hardware Testing)
2. NoSQL (under Concepts Applied)
3. MQTT & QoS (under Concepts Applied)

Reviewed:
1. Monitoring Internal Environmental Data (under Literature Review)

**Comment by yucan-yu** [comment]
Section 4 all completed; parts on Node-RED, MQTT, etc. have also been written.

**Comment by ong-yi-xuan** [comment]
completed sections on:
**Under Deployment**
Internal Environmental Data 

**Under Systems Test**
Firmware Testing

todo:
literature review: nodered vs telegraf

**Comment by yucan-yu** [comment]
Completed section on Software Architecture.

**Comment by danialhbma** [comment]
Fixed report format, pls plz PLZ PLS PLEASE dont touch the headers or subheader format u will ruin the whole report @everyone

**Comment by ong-yi-xuan** [comment]
completed literature review on backend technologies (nodered vs telegraf)
