### ISSUE TITLE
Research: Decide on Types of Analysis

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#33]
Aim to cover analysis on the following datasets collected:

- CO2
- Light sensor 
- Water flow
- Humidity
- Temperature (in the container)

Weather data (From NEA & OpenWeather API)
- Hourly or Monthly/Seasonal
- Temperature
- Rainfall 

Calculations & Analysis will cover:

- Power consumption averages 
- Water usage (water charges as well)
- Temperature & estimate power usage of aircon

All of these calculations will be included in a calculator created for the crop scientists to input their power consumption data and receive as estimate on the charges that will be incurred.

Finally, the data analysis will also include suggestions for future-proofing the project further. 

Suggestions for future proofing:
- Which ideal season to grow the plants in terms of power efficiency?
- Power consumption of growing plants during day vs at night (turn on lights during day or at night)
- How our project can fit different environments/locations with additional or lesser hardware and variables

**Comment by yucan-yu** [comment]
Currently, after assessing possibilities and limitations, team has decided to work on:


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91590888/cf567a57-fe94-4c37-872a-557cb1116075)

Each analysis will be followed up on separate issues assigned to respective team member.
