### ISSUE TITLE
Implementation: Testing of Clamps vs Tuya Sockets

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#38]
Collect clamp measurements on the light and water pump plugs, ideally for 1 hour, and retrieve delta from the difference in (Clamps and Tuya Sockets) values.

**Comment by yucan-yu** [comment]
Code implemented; calculating power using formula (Power = VRMS * IRMS). In the midst of clarifying with Prof Fauzi on the correctness of approach on retrieving the IRMS value.

**Comment by yucan-yu** [comment]
Prof Fauzi clarified formula should be Power = AC current * 240V - updated accordingly.

Code implementation complete, to undergo testing soon.

**Comment by yucan-yu** [comment]
Clamp code committed to remote repository; sensor handed over to @danialhbma for further calibration and testing.

**Comment by danialhbma** [comment]
Managed to get the clamps connected to the M5StickC, but could not find any suitable cables to obtain readings from. Values were not accurate, so we decided that the clamps would not be used in the final product.
