### ISSUE TITLE
Analysis: Variables that can contribute to a change in power consumption

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#39]
weightage - pie chart (e.g., 70% lightning 10% pump?)

**Comment by ong-yi-xuan** [comment]
plan:
- get power consumption of all variables > find weightage of each variable
- display weightage of all variables in a pie chart form

**Comment by ong-yi-xuan** [comment]
analysis code does:
- gets the power consumption of rack LED lights and water pumps from data
- using researched data, find the avg and max power consumption of aircons
- get total power consumption
- get % that rack LED lights, water and aircon contributes to avg and max power consumption

**Comment by ong-yi-xuan** [comment]
sample output:


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/21c96b09-28d4-4ce6-8b26-c9fa919f48d2)

to look into issue where total percentage adds up to 100.01%

**Comment by ong-yi-xuan** [comment]
- fixed formula for calculating aircon power consumption ✅
- expanded on rack light function to get power consumption by LED colour + estimate power consumption based on number of racks with each LED colour ✅
- expanded water function to estimate power consumption based on number of racks ✅
- neatened up code with comments ✅
- created pie chart from calculations ✅

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/05b8bba8-4ab1-4f5e-a3d0-3d08cefaf101)

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/9b3ad39c-dbc2-4b27-8e04-343465eb2e5e)
