### ISSUE TITLE
Analysis: Power consumption cost of running one container in the current state

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#41]
In conjunction with the calculator tool, this analysis will include the costs of running the container in its current state. This includes:
- cost of running ALL the water pumps
- cost of running ALL the LED strips
- estimated cost of running two aircons
- estimated cost of ceiling lights (using average visitor trends, e.g., lights are turned on average 1 hour per visit/10 hours a month)

break down by racks (how many pumps & lights per rack) - justify breakdown

**Comment by Yapping72** [comment]
Aircon 
﻿MODEL: STA-024SPWM
Power supply (Ph-V-Hz): 208-230V~50/60Hz,1Ph

Cooling:
Capacity (Btu/h): 24000
Running current (A): 5.1
Operating Power Input (W): 1230.0

MINIMUM CIRCUIT AMPACITY (A): 18
MAX FUSE (A): 25

Compressor:
Type: ROTARY
Brand: ECOLINE
Capacity (Btu/h): 24000
Input (W): 1970
Running current (RLA) (A): 12
Refrigerant oil/oil charge (ml): ESTER OIL VG74/670

Indoor Fan Motor:
Input (W): 58(Output)
RLA (A): 0.4
Speed (Hi/Mi/Lo) (r/min): 1100/900/700

Indoor air flow (Hi/Mi/Lo) (m3/h): 1000/780/600
Indoor air flow (Hi/Mi/Lo) (CFM): 580/450/353
Indoor noise level (Hi/Mi/Lo) (dB(A)): 45.5/-/33

Indoor Unit:
Dimension(WDH) (mm): 1080x226x335
Packing (WDH) (mm): 1155x415x315
Net/Gross weight (Kg): 13.2/16.8

Outdoor Fan Motor:
Input (W): 58(Output)
RLA (A): 0.6
Speed (r/min): 940

Outdoor air flow (m3/h): 2700
Outdoor air flow (CFM): 1590
Outdoor noise level (dB(A)): 59

Outdoor unit:
Dimension(WDH) (mm): 845x363x702
Packing (WDH) (mm): 965x395x755
Net/Gross weight (Kg): 47.7/51.0

Refrigerant type (g): R407C/1500g
Design pressure (PSIG): 550/340 PSIG

Refrigerant piping:
Liquid side/Gas side (mm(inch)): ϕ9.53/ϕ15.9(3/8" / 5/8")
Max. refrigerant pipe length (m): 30
Max. difference in level (m): 20

Connection wiring: 16AWG*4 Stranded, unshielded
Thermostat type: Remote Control

Operation temperature:
Indoor (°C): 17 ~ 32

**Comment by chococtea** [comment]
As of now,

1. Linear regression for the racks' power consumption - will do profiling of each rack we monitored 
2. For unmonitored devices, power consumption will be calculated based on their specifications and their timing schedule.

**Comment by chococtea** [comment]
Info from crop scientists/research:

- Grow lights' and water pump's specifications should be roughly the same across the 9 racks.
 
- For purple grow lights, it's made of red and blue lights as plants take in more of this to grow (according to the plant growth light spectrum chart). So, they use purple lights for new plants. Then for the white ones, they still have the red and blue light and are usually when the plants are already growing.

- Type of plants in each rack: (top layer (opp side of the door) - Rack 1 - 5, bottom layer (same side of the door) Rack 6 - 9)
  - rack 1 - lettuce, rack 2 - lettuce & sorrel, rack 3 - empty, rack 4, 5, 7, 8 & 9 - strawberries and rack 6 - basil

**Comment by chococtea** [comment]
Working on retrieving power consumption data and creating a document for the rack profiling to be used in the training of linear regression model which is done in python.

**Comment by chococtea** [comment]
Wrote the codes for the linear regression model for racks' power consumption. As of now, the script handles preprocessing of data, model training, and model predictions. For predictions, the model can predict the daily power consumption of each rack's devices - light & water pump for the entire month and export it as a csv file.

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/92836838/889436dd-4399-426a-8bd0-a10fa6130ead)

But sometimes the values for timer is in negative. So will look into this and determine what causes this. Other than that, will be working on the cost calculator script.

**Comment by chococtea** [comment]
Nevermind, found an issue with the data preprocessing. will fix that and try the model fitting again.

**Comment by chococtea** [comment]
okie, fixed the data preprocessing part and fitted the model again. predicted values now look more reasonable. will proceed with the estimation of cost part

**Comment by chococtea** [comment]
Cost calculator is currently working but will need to modify again once there's more data on the operating hours of the ceiling lights and the formula for aircon consumption.

current output:
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/92836838/9d8049b8-299b-4fe1-99d5-7cc41cb23ec6)

**Comment by chococtea** [comment]
Made a few changes to the code:

- Changed Aircon's specifications to standardise with the others' analysis.
- Removed the table and plotted a bar chart instead.
- Bar chart is saved into results folder.

Current Output:
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/92836838/9cc59f79-1bbf-4c16-941b-30e6c98823f9)
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/92836838/b974525a-d7ed-4317-b2fb-a255226a48b5)

**Comment by chococtea** [comment]
Modified the bar chart visualisation to include the total sum (at the side), consistent Y axis label (cost ($) & power consumption (kWh)), changed 'estimated' to 'predicted' in the title and incldued the month and year in the tilte.

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/92836838/7efc5981-97d0-4fc2-a44c-c27a8dc686e4)
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/92836838/478dcfb4-9eeb-47fd-8bdb-bdc4fed8040d)
