### ISSUE TITLE
Implementation: Setup Reverse Proxy

### ISSUE THREAD

**Issue by ong-yi-xuan** [danialhbma/ITP-SE12-Power-Monitoring#45]
configure reverse proxy for grafana

**Comment by ong-yi-xuan** [comment]
- nginx docker container set up ✅
- grafana rerouted nginx proxy ✅

still have to fix CORS policy issue when query api

**Comment by yucan-yu** [comment]
CORS policy issue fixed for query API and update InfluxDB.

**Comment by ong-yi-xuan** [comment]
grafana running on https using nginx
