### ISSUE TITLE
Research + Implementation: Correlation Algorithm

### ISSUE THREAD

**Issue by chococtea** [danialhbma/ITP-SE12-Power-Monitoring#46]
Research on Correlation Algorithm, and find out how it can help us determine if there is a relationship between the external environment and power consumption. Also, to come up with a script for the correlation analysis.

**Comment by chococtea** [comment]
External environment variables: avg temp, avg rainfall, min temp, and max temp of the month.
Try to correlate with the monthly power consumption --> given by Mr Kwek

Need to look into getting past data for the external environment variables as the monthly power consumption data given is past data.

**Comment by chococtea** [comment]
For past data, came upon an issue with doing monthly correlation due to insufficient data for Power Consumption. So, will look into these 3 methods:

Option 1 - Dividing the Total Monthly Power Consumption by the number of days in that month to get the average Daily Power Consumption (Monthly correlation)
Option 2 - Correlate all 8 months of data together rather than doing a monthly correlation
Option 3 - Estimating the Daily Power Consumption based on our current data (Tuya Devices)

**Comment by chococtea** [comment]
also, all the past data are in csv format.

- External environment variables are taken from http://www.weather.gov.sg/climate-historical-daily/
- Downloaded the csv files from Oct 2022 till May 2023 (To match with the number of monthly power consumption data given by Mr Kwek)
- Created a csv file for Monthly Power Consumption Data.

So, wrote a python script that reads and format csv files before writing into influxdb.

**Comment by chococtea** [comment]
So, regarding this https://github.com/danialhbma/ITP-SE12-Power-Monitoring/issues/46#issuecomment-1636163725, I will be going with Option 2.

**Option 1 - Dividing the Total Monthly Power Consumption by the number of days in that month to get the average Daily Power Consumption (Monthly correlation)**

- Tried out for an online Pearson Correlation Calculator to test out Option 1 and see the result.
- Did 2 months - Oct 22 & Nov 22 and 2 variables each (Daily Power Consumption & Daily Mean Temp)
- Tried 2 different online calculators - both gave the same result which is NaN.
- NaN usually occurs when there’s no linear relationship between variables, insufficient or missing data, or constant or near-constant values.

Decision - Not doing this as the results cannot be used as its NaN.

**Option 2 - Correlate all 8 months of data together rather than doing a monthly correlation**

- Tested the same way as Option 1.
- Did all the months and 2 variables each (Total Monthly Power Consumption & Average Monthly Mean Temp)
- Both calculators gave me the same result which is 0.53 (A good sign)

Decision: Using this as the results can be used for further analysis etc.

**Option 3 - Estimating the Daily Power Consumption based on our current data (Tuya Devices)**
Will not be testing this out. Since it’s using estimation values, the result won't be significant or similar to option 1.

**Comment by chococtea** [comment]
Working on the correlation analysis script

**Comment by chococtea** [comment]
Finished the correlation calculator part  - left with the storing of result into a db (currently just calculating correlation and printing put the result)

For past data, the correlation between total power consumption and external environment variables is successful.


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/92836838/af91250f-7c63-45ca-8df6-bc8a8c13b5ea)


For future/current data, came upon an issue of missing one of the external environment variables which is daily rainfall as our weatherAPI doesn't cover this. So, the monthly correlation won't include this variable (only max_temp, min_temp and mean_temp).

**Comment by chococtea** [comment]
Code is in repo. Any modifications to the code (mainly the writing into db and maybe the reading data from csv instead of directly from db) will be handled by Yapping (will provide assistance if needed), so will close this issue alr.

**Comment by Yapping72** [comment]
No longer need to write to db, removed requirement to update analysis into db. Analysis will be outputted as heat maps as shown below (WIP). code to generate report will pick up and paste heatmaps into pdf.

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/54227281/01c2d68f-ab1f-4029-beb7-b8bced785c3c)
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/54227281/efefeaae-dc8d-4473-afcd-76f1fc688363)
