### ISSUE TITLE
Implementation: Create Calculator Tool

### ISSUE THREAD

**Issue by ong-yi-xuan** [danialhbma/ITP-SE12-Power-Monitoring#47]
create calculator tool in dashboard that allows users to input variables and estimate power consumption from inputted variables

**Comment by yucan-yu** [comment]
API endpoint set up for POST requests; require confirmation of formula before deployment.

**Comment by yucan-yu** [comment]
Grafana and nginx configurations have been deployed on our test server; code pushed for @ong-yi-xuan to try calling the endpoint via dashboard and note any response/error.

**Comment by ong-yi-xuan** [comment]
- flask api deployed on port 8080 on test server
- firewall rule configured
- endpoint called from grafana dashboard and postman, both returned error 404

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/65bee5ae-0a53-4bb5-a115-808b26dbdad3)

formula can potentially reuse from variables_that_affect_power.py -> uses our collected data to estimate power consumption for different rack LED light colours and water pumps

**Comment by yucan-yu** [comment]
Issue fixed with effort by @ong-yi-xuan, have retrieved "calculation" results:


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91590888/90f7ed41-3ae7-4103-81ab-b1738a816f2f)

**Comment by ong-yi-xuan** [comment]
formula added to flask api
- takes in the values in the form below to calculate power consumption + difference in power consumption  between simulated setup and current setup (both values are power consumption **per month**)

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/368eebdf-9e6e-4835-89b7-0e84e2e31f90)

wip: fixing deployment of api on docker container in test server

**Comment by ong-yi-xuan** [comment]
api with calculations deployed on docker container


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/a7ee16e0-39db-4b72-81cc-603e231fe654)

**Comment by ong-yi-xuan** [comment]
issues/analysis merged - continued in #59
