### ISSUE TITLE
Bug Fix: Look into missing data points

### ISSUE THREAD

**Issue by ong-yi-xuan** [danialhbma/ITP-SE12-Power-Monitoring#48]
Find out what is causing missing data point from M5Sticks

**Comment by yucan-yu** [comment]
Subscriber (Node-RED) confirmed to be running QoS 2, hence it's expected to receive messages exactly once as it consistently initiates a handshake process until it receives its intended message.

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91590888/60df8459-9d1d-46d3-8c94-e5cb6a6dcb60)

Have to look into the m5mqtt library - may not be running QoS 1 despite defining it through a parameter.

**Comment by yucan-yu** [comment]
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91590888/769a8dfe-96a6-4f4f-925c-f2ae836567b1)

**Comment by yucan-yu** [comment]
From the M5Stack community, we can confirm that QoS 1 and 2 has been implemented (although QoS 2 is a little unstable).
Link: https://community.m5stack.com/topic/4090/core2-hivemq/27

Our code uses QoS 1, which ensures messages are sent at least once:
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91590888/f1afd5f6-7e1c-4b05-affe-b5f8ff0877bd)

**Comment by yucan-yu** [comment]
Based on observations from visit via the farm, missing data points is likely due to instability in either:
1. Router
2. wifiCfg.doConnect()
