### ISSUE TITLE
Bug Fix: Review Analysis

### ISSUE THREAD

**Issue by ong-yi-xuan** [danialhbma/ITP-SE12-Power-Monitoring#56]
Individually review respective assigned analysis task to ensure they meet client's requirements.

**Comment by yucan-yu** [comment]
General observation that all analysis can be merged into calculator tool; to be confirmed with other members.

**Comment by yucan-yu** [comment]
Analysis merged with calculator tool. Additional scripts will be HOTO'ed as "Future Work" consideration.
