### ISSUE TITLE
Research: Tuya Pricing

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#6]
Pricing plans decided, left to Prof Fauzi to decide

**Comment by chococtea** [comment]
**Available Plans for Tuya Cloud:**
![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/92836838/d230f08d-bfe7-4479-a116-ccca539760a7)

Final decision made on 4th May 2023.
Decision: To keep using the trial edition of Tuya IoT Platform and ask for extension whenever needed.
