### ISSUE TITLE
Submission: Final Presentation

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#61]
1st August, Tuesday 4pm @ SIT@Dover, DV-SHED-SR1B

20 mins of Presentation
10 mins of Demonstration
15 mins of Q&A
15 mins of buffer time

**Comment by yucan-yu** [comment]
Done and dusted. Good job everyone, think we did a pretty solid job during both presentation and Q&A.

Congratulations, we made it! Let's just pray the results will fairly reflect all our deliverables and efforts.
