### ISSUE TITLE
Implementation: Sensor Data Retrieval

### ISSUE THREAD

**Issue by ong-yi-xuan** [danialhbma/ITP-SE12-Power-Monitoring#9]
Configure M5sticks to:
- retrieve data from sensors (light, temperature, c02)
- publish sensor data via MQTT

**Comment by ong-yi-xuan** [comment]
sensor data retrieved:
- temperature ✅
- c02 ✅
- humidity ✅

work in progress:
- light

**Comment by ong-yi-xuan** [comment]
light sensor data retrieved ✅

all data that is published by m5sticks can be seen in node-red (mqtt subscriber)

**Comment by ong-yi-xuan** [comment]
- to test detection range of light sensor
- set up water flow sensor and ADC
- retrieve data from water flow sensor

**Comment by ong-yi-xuan** [comment]
flow sensor and ADC to be moved to sprint 2

**Comment by yucan-yu** [comment]
^ refer to new issue #18
